---	
apiVersion: v1	
kind: Pod	
metadata:	
  name: a-tools	
  namespace: test	
spec:	
  serviceAccountName: a	
  containers:
    - name: a
      image: containous/whoami:v1.0.1

---
apiVersion: v1
kind: Pod
metadata:
  name: b-v1
  namespace: test
  labels:
    app: b
    version: v1
spec:
  serviceAccountName: b
  hostname: b-v1
  containers:
    - name: b
      image: containous/whoami:v1.0.1

---
apiVersion: v1
kind: Pod
metadata:
  name: b-v2
  namespace: test
  labels:
    app: b
    version: v2
spec:
  serviceAccountName: b
  hostname: b-v2
  containers:
    - name: b
      image: containous/whoami:v1.0.1
