---
apiVersion: v1
kind: Service
metadata:
  name: b
  namespace: test
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: web
  selector:
    app: b

---
apiVersion: v1
kind: Service
metadata:
  name: b1
  namespace: test
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: web
  selector:
    app: b
    
---
apiVersion: v1
kind: Service
metadata:
  name: b2
  namespace: test
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: web
  selector:
    app: b
    
---
apiVersion: v1
kind: Service
metadata:
  name: b-v1
  namespace: test
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: web
  selector:
    app: b
    version: v1

---
apiVersion: v1
kind: Service
metadata:
  name: b-v2
  namespace: test
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: web
  selector:
    app: b
    version: v2
