---
kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha1
metadata:
  name: a-b
  namespace: test
destination:
  kind: ServiceAccount
  name: true
  namespace: test
specs:
- kind: HTTPRouteGroup
  name: app-routes
  namespace: 0
  matches:
  - foo
sources:
- kind: ServiceAccount
  name: a
  namespace: false
