---
apiVersion: v1
kind: Pod
metadata:
  name: a
  namespace: test
spec:
  serviceAccountName: a
  containers:
    - name: a
      image: containous/whoami:v1.0.1

---
apiVersion: v1
kind: Pod
metadata:
  name: b
  namespace: test
  labels:
    app: b
spec:
  serviceAccountName: b
  containers:
    - name: b
      image: containous/whoami:v1.0.1

---
apiVersion: v1
kind: Pod
metadata:
  name: c
  namespace: test
spec:
  serviceAccountName: c
  containers:
    - name: c
      image: containous/whoami:v1.0.1

---
apiVersion: v1
kind: Pod
metadata:
  name: d
  namespace: test
  labels:
    app: d
spec:
  serviceAccountName: d
  containers:
    - name: d
      image: containous/whoami:v1.0.1

---
apiVersion: v1
kind: Pod
metadata:
  name: e
  namespace: test
  labels:
    app: e
spec:
  serviceAccountName: e
  containers:
    - name: e
      image: containous/whoami:v1.0.1

---
apiVersion: v1
kind: Pod
metadata:
  name: tcp
  namespace: test
  labels:
    app: tcp
spec:
  serviceAccountName: tcp
  containers:
    - name: tcp
      image: containous/whoami:v1.0.1
