---
apiVersion: v1
name: maesh
version: 1.0.0
appVersion: v1.0.0
description: Maesh - Simpler Service Mesh
keywords:
- traefik
- mesh
home: https://containo.us/
maintainers:
- name: emilevauge
  email: emile@vauge.com
- name: dtomcej
  email: daniel@containo.us
- name: mmatur
  email: michael@containo.us
engine: gotpl
icon: https://avatars0.githubusercontent.com/u/16349663?s=200&v=4
